version: '3.1'
services:
  bullboard:
    image: deadly0/bull-board
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 4444:3000
  redis:
    image: redis:7.0.0
    ports:
      - 6379:6379
